baseURL = 'https://taude.xyz/'
languageCode = 'en-us'
title = 'Welcome to taude.xyz'
theme= 'archie'

[module]
  [[module.mounts]]
    source = '/Users/tprekaski/Library/Mobile Documents/com~apple~CloudDocs/Todd's Obsidian Vault/1 Projects/taude.xyz Blog/'
    target = 'content'
